name: npm-publish
on:
  push:
    branches:
      - master
jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    
    - name: Check if version has been updated
      id: check
      uses: EndBug/version-check@master
      with:
        diff-search: true
        file-name: package.json
        file-url: https://unpkg.com/szfe-ui/package.json
        assume-same-version: old
        
    - name: Log when changed
      if: steps.check.outputs.changed == 'true'
      run: 'echo "Version change found in commit ${{ steps.check.outputs.commit }}! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'
      
    - name: Set up Node.js
      if: steps.check.outputs.changed == 'true'
      uses: actions/setup-node@master
      with:
        node-version: 13.11.0

    - name: Install
      if: steps.check.outputs.changed == 'true'
      uses: CultureHQ/actions-yarn@master
      with:
        args: install
        
    - name: Build
      if: steps.check.outputs.changed == 'true'
      run: 'sudo npm run build'
      
    - name: Publish if version has been updated
      if: steps.check.outputs.changed == 'true'
      uses: pascalgn/npm-publish-action@1.2.0
      with:
        commit_pattern: "^Release (\\S+)"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
